"""
Django settings for blog_cbv project.
Generated by 'django-admin startproject' using Django 5.2.13.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
import os
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []
# Ставим DEBUG = False
#ALLOWED_HOSTS = ['127.0.0.1'] # Должен быть заполнен. Иначе не заработает при DEBUG = False

#DEBUG = os.getenv('DEBUG', 'False') == 'True' # False

# if os.getenv('ALLOWED_HOSTS'):
#     ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').replace(' ', '').split(',')
# else:
#     ALLOWED_HOSTS = []

if os.getenv('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS').replace(' ', '').split(',')

INTERNAL_IPS = [
    '127.0.0.1', # Можно оставить в продакшене
]

SITE_ID = 1 # Нужно для карты сайта

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # важно чтобы было в наличии для полноценной работы тулбара
    # ------------------------ Добавленные приложения
    'apps.blog.apps.BlogConfig', # Подключаем конфигурацию
    'mptt',
    'django_mptt_admin',
    'debug_toolbar',  # приложение тулбара
    'apps.accounts',
    'taggit', # Добавление функциональности тегирования
    'taggit_serializer',# Добавление тегов в API
    'django_recaptcha', # Добавление функциональности ReCAPTCHA
    'ckeditor_uploader', # Добавление функциональности редактора WYSIWYG
    'ckeditor',
    'django.contrib.sites', # Нужно для карты сайта
    'django.contrib.sitemaps', # Нужно для карты сайта
    'django.contrib.postgres', # Нужно чтобы работал поиск
    'social_django', # Вход через соцсети
    'rest_framework', # Добавляем API
    'apps.blog_cbv_api.apps.BlogCbvApiConfig', # Регистрируем новое приложение API \ Созадётся автоматически
    'django_filters', # Удобная фильтрация в API
    'rest_framework.authtoken', # Аутентификация в API
    'drf_spectacular', # Добавление схемы сайта
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],  # new
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.LimitOffsetPagination',  # new
        'PAGE_SIZE': 5,  # new
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        "rest_framework.authentication.TokenAuthentication",  # new
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # new
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Blog 2.0 API Project",
    "DESCRIPTION": "A sample blog to learn about DRF",
    "VERSION": "2.0.0",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Middleware тулбара - DjDT модуль
    'apps.accounts.middleware.ActiveUserMiddleware',  # Определяет активного пользователя
]

ROOT_URLCONF = 'blog_cbv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # важно чтобы было в наличии для полноценной работы тулбара
        'DIRS': [BASE_DIR / 'templates'], # Было []
        'APP_DIRS': True, # важно чтобы было True для полноценной работы тулбара
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # new code
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]

WSGI_APPLICATION = 'blog_cbv.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASS'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC_URL = 'static/'
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static/'
STATICFILES_DIRS = [BASE_DIR / 'templates/js/']
# STATICFILES_DIRS = [ BASE_DIR / 'apps/blog/static' ]

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': 'full',
        'height': 300,
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'cache',
    }
}

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #Продакшен
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #Разработка

# Конфигурация сервера электронной почты
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# EMAIL_PORT: Задаёт порт SMTP-сервера. Обычно используется порт 587 для TLS или 465 для SSL/TLS.
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend', # Базовая серверная часть аутентификации,
)

# social auth configs for GitHub
SOCIAL_AUTH_GITHUB_KEY = os.getenv('GITHUB_KEY')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('GITHUB_SECRET')

# social auth configs for Google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_SECRET')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Настройка логгирования
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "custom": {
            "format": "[{levelname}] [{asctime}] [{name}] [{message}]",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "custom",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "blog_cbv_debug.log",
            "formatter": "custom",
        },
    },

    "root": {
        "handlers": ["file"],
        "level": "INFO",
    },
}

